### ISSUE TITLE
Can't find '__main__'

### ISSUE THREAD

**Issue by ccgguy** [NikitaCern/TaleSpire_Generator#9]
C:\Users\Noble\Documents\GitHub\TaleSpire_Generator>python generator import Generator
C:\Users\Noble\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe: can't find '__main__' module in 'C:\\Users\\Noble\\Documents\\GitHub\\TaleSpire_Generator\\generator'

I may be overcomplicating it, what is the command to run the generator?
Sorry for being dumb. <3

**Comment by NikitaCern** [comment]
see "Basic Use" in the README.md.
It outlines basic usage of the tool. if something is unclear in the given example, leave a comment, with what is unclear.

**Comment by ccgguy** [comment]
OK, so I will keep it simple.

"Create a file example.py, which contains:"
'CODE' in a .txt -> change to .py...

And save it where? (Directory)

Once saved, do you simply use

'Filepath'> python 'filename' 
to run it?
E.G. 

1. I make example.py.

2. I put example.py in folder 'inputs'.

in CMD I type:
"C:\Users\Noble\Documents\GitHub\TaleSpire_Generator\inputs> python example.py -> Return.

Generator outputs to json?

So simple;
1. What do I type to run the file ('example.py')?
python example.py
python -r example.py
python make it work cause I am done command here<


Thanks for letting me stupid :D on the plus side, you get to see the pain of the dev team trying to make a product stupid proof.

**Comment by ccgguy** [comment]
C:\Users\Noble\Documents\GitHub\TaleSpire_Generator>python -m unittest

Asset: ....
AssetManager: ....
Config: .
Encode/Decode: .
Generate (last one takes ~30s, be patient!): ...............F
Prop: ..
Quad: ....
Settings: ...
Tiles: ..
======================================================================
FAIL: test_timedGeneration (test.test_generator.TestGenerator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Noble\Documents\GitHub\TaleSpire_Generator\test\test_generator.py", line 444, in test_timedGeneration
    self.assertLessEqual(end_time-start_time, 30, msg="Generation takes too long!")
AssertionError: 33.12078237533569 not less than or equal to 30 : Generation takes too long!

----------------------------------------------------------------------
Ran 37 tests in 36.556s

FAILED (failures=1)

**Comment by ccgguy** [comment]
> C:\Users\Noble\Documents\GitHub\TaleSpire_Generator>python -m unittest
> 
> # Asset: ....
> AssetManager: ....
> Config: .
> Encode/Decode: .
> Generate (last one takes ~30s, be patient!): ...............F
> Prop: ..
> Quad: ....
> Settings: ...
> Tiles: ..
> ## FAIL: test_timedGeneration (test.test_generator.TestGenerator)
> Traceback (most recent call last): File "C:\Users\Noble\Documents\GitHub\TaleSpire_Generator\test\test_generator.py", line 444, in test_timedGeneration self.assertLessEqual(end_time-start_time, 30, msg="Generation takes too long!") AssertionError: 33.12078237533569 not less than or equal to 30 : Generation takes too long!
> 
> Ran 37 tests in 36.556s
> 
> FAILED (failures=1)

FIXED BY increasing time: C:\Users\Noble\Documents\GitHub\TaleSpire_Generator>python -m unittest

Asset: ....
AssetManager: ....
Config: .
Encode/Decode: .
Generate (last one takes ~30s, be patient!): ................
Prop: ..
Quad: ....
Settings: ...
Tiles: ..
----------------------------------------------------------------------
Ran 37 tests in 34.808s

OK

C:\Users\Noble\Documents\GitHub\TaleSpire_Generator>

**Comment by ccgguy** [comment]
OK so I; 
1. deleted the whole the repo to start fresh.
2. Pulled a new repository.
3. Added index.json from talespire directory
4. Ran pip install -r requirements.txt
5. Ran python .\firstTimeSetup.py
6. Ran python -m unittest
- failed
7. changed timeout to 300 seconds in test_generator on line 444.
8. Ran python -m unittest
9. Passed 'OK' in 34.808s.
10. Created 'example.py' in main directory as shown here:
![No such file, but there is](https://user-images.githubusercontent.com/30777923/149247803-216aade4-5878-4d4e-95ff-03f24d073f72.PNG)

11. Ran 'python .\example.py '
12. Got this error: 
"C:\Users\Noble\Documents\GitHub\TaleSpire_Generator>python .\example.py
python: can't open file 'C:\Users\Noble\Documents\GitHub\TaleSpire_Generator\example.py': [Errno 2] No such file or directory"

**Comment by ccgguy** [comment]
> Your example.py file is actually named exapmle.py.txt You need to enable show file extensions on your machine.

.... I just reset windows, I can't believe I missed that.

It works! congrats!
